version: '3'
services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src

